/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGApiResponse.h
 *
 * Describes the result of uploading an image resource
 */

#ifndef SWGApiResponse_H_
#define SWGApiResponse_H_

#include <QJsonObject>
#include <QStringList>


#include <QString>

#include "SWGObject.h"

namespace Swagger {

class SWGApiResponse: public SWGObject {
public:
    SWGApiResponse();
    SWGApiResponse(QString const &json);
    virtual ~SWGApiResponse();
    void init();
    void cleanup();

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject const &json) override;
    void fromJson(QString const &jsonString) override;

    
    qint32 getCode() const;
    void setCode(qint32 const &code);

    
    QString getType() const;
    void setType(QString const &type);

    
    QString getMessage() const;
    void setMessage(QString const &message);


    virtual bool isSet() const override;

private:
    
    qint32 code;
    bool code_isSet;

    
    QString type;

    
    QString message;

};

}

#endif /* SWGApiResponse_H_ */
