/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGCurrency.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {



SWGCurrency::SWGCurrency(QString const &json) {
    init();
    this->fromJson(json);
}

SWGCurrency::SWGCurrency() {
    init();
}

SWGCurrency::~SWGCurrency() {
    this->cleanup();
}

void SWGCurrency::init() {
    }

void SWGCurrency::cleanup() {
}

void SWGCurrency::fromJson(QString const &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void SWGCurrency::fromJsonObject(QJsonObject const &pJson) {
    mGenericData = pJson;
    }

QString SWGCurrency::asJson () const
{
    QJsonObject const obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject SWGCurrency::asJsonObject() const {
    QJsonObject obj;
    
    return obj;
}


bool SWGCurrency::isSet() const{
    bool isObjectUpdated = false;
    do{
    }while(false);
    return isObjectUpdated;
}
}

