/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGCategory.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {



SWGCategory::SWGCategory(QString const &json) {
    init();
    this->fromJson(json);
}

SWGCategory::SWGCategory() {
    init();
}

SWGCategory::~SWGCategory() {
    this->cleanup();
}

void SWGCategory::init() {
    id = 0L;
    id_isSet = false;}

void SWGCategory::cleanup() {
}

void SWGCategory::fromJson(QString const &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void SWGCategory::fromJsonObject(QJsonObject const &pJson) {
    mGenericData = pJson;
    
    id_isSet = pJson.contains("id");
    id = fromJsonValue<qint64>(pJson["id"]);


    name = fromJsonValue<QString>(pJson["name"]);

}

QString SWGCategory::asJson () const
{
    QJsonObject const obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject SWGCategory::asJsonObject() const {
    QJsonObject obj;
    
    obj.insert("id", QJsonValue(id));

    obj.insert("name", toJsonValue(name));

    return obj;
}


qint64 SWGCategory::getId() const {
    return id;
}
void SWGCategory::setId(qint64 const &id) {
    this->id = id;
    this->id_isSet = true;
}


QString SWGCategory::getName() const {
    return name;
}
void SWGCategory::setName(QString const &name) {
    this->name = name;
}


bool SWGCategory::isSet() const{
    bool isObjectUpdated = false;
    do{
        
        if(id_isSet){ isObjectUpdated = true; break;}
        
        if(!name.isNull()){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

