/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Based on http://www.creativepulse.gr/en/blog/2014/restful-api-requests-using-qt-cpp-for-linux-mac-osx-ms-windows
 * By Alex Stylianos
 *
 **/

#ifndef SWG_HTTPREQUESTWORKER_H
#define SWG_HTTPREQUESTWORKER_H

#include <QObject>
#include <QString>
#include <QMap>
#include <QNetworkAccessManager>
#include <QNetworkReply>



namespace Swagger {

enum SWGHttpRequestVarLayout {NOT_SET, ADDRESS, URL_ENCODED, MULTIPART};

class SWGHttpRequestInputFileElement {

public:
    QString variable_name;
    QString local_filename;
    QString request_filename;
    QString mime_type;

};


class SWGHttpRequestInput {

public:
    QString url_str;
    QString http_method;
    SWGHttpRequestVarLayout var_layout;
    QMap<QString, QString> vars;
    QMap<QString, QString> headers;
    QList<SWGHttpRequestInputFileElement> files;
    QByteArray request_body;

    SWGHttpRequestInput();
    SWGHttpRequestInput(QString v_url_str, QString v_http_method);
    void initialize();
    void add_var(QString key, QString value);
    void add_file(QString variable_name, QString local_filename, QString request_filename, QString mime_type);

};

class SWGHttpRequestWorker : public QObject {
    Q_OBJECT

public:
    QByteArray rawResponse;
    QNetworkReply * reply = nullptr;
    QNetworkReply::NetworkError error_type;
    QString error_str;
    QString msg; // debug message

    explicit SWGHttpRequestWorker(QObject *parent = 0);
    virtual ~SWGHttpRequestWorker();

    virtual void processResult() {}

    QString http_attribute_encode(QString attribute_name, QString input);
    void execute(SWGHttpRequestInput &input);
    static QSslConfiguration* sslDefaultConfiguration;

    bool isFinished() const {return reply && reply->isFinished();}
    bool isRunning() const {return reply && reply->isRunning();}
    QNetworkRequest rawRequest() const {return reply ? reply->request() : QNetworkRequest();}
    int httpStatusCode() const {return reply ? reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt() : 0;}
    bool isValid() const {return isFinished() && error_type==QNetworkReply::NoError && httpStatusCode() < 400;} 

Q_SIGNALS:
    void finished();
    void error(QNetworkReply::NetworkError code);

private:
    QNetworkAccessManager *manager;

private Q_SLOTS:
    void on_reply_finished();

};

}

#endif // SWG_HTTPREQUESTWORKER_H
