/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_OBJECT_H_
#define _SWG_OBJECT_H_

#include <QSharedPointer>
#include <QJsonValue>
#include <QJsonObject>
#include <QJsonDocument>

namespace Swagger {

class SWGObject {
public:
    virtual ~SWGObject() {}

    virtual QString asJson () const {
        return QJsonDocument(mGenericData).toJson(QJsonDocument::Compact);
    }
    virtual QJsonObject asJsonObject() const {
        return mGenericData;
    }
    virtual void fromJsonObject(QJsonObject const &json) {
        mGenericData = json;
    }
    virtual void fromJson(QString const &jsonString) {
        mGenericData = QJsonDocument::fromJson(jsonString.toLocal8Bit()).object();
    }
    virtual bool isSet() const {
        return mGenericData.isEmpty();
    }
protected:
    QJsonObject mGenericData;
};

}

#endif /* _SWG_OBJECT_H_ */
