/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGPet.h
 *
 * A pet for sale in the pet store
 */

#ifndef SWGPet_H_
#define SWGPet_H_

#include <QJsonObject>
#include <QStringList>


#include "SWGCategory.h"
#include "SWGTag.h"
#include <QList>
#include <QString>

#include "SWGObject.h"

namespace Swagger {

class SWGPet: public SWGObject {
public:
    SWGPet();
    SWGPet(QString const &json);
    virtual ~SWGPet();
    void init();
    void cleanup();

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject const &json) override;
    void fromJson(QString const &jsonString) override;

    
    qint64 getId() const;
    void setId(qint64 const &id);

    
    SWGCategory getCategory() const;
    void setCategory(SWGCategory const &category);

    
    QString getName() const;
    void setName(QString const &name);

    
    QList<QString> getPhotoUrls() const;
    void setPhotoUrls(QList<QString> const &photo_urls);

    
    QList<SWGTag> getTags() const;
    void setTags(QList<SWGTag> const &tags);

    enum status { 
        status_SWGUndefined=-1,
        status_available,
        status_pending,
        status_sold
    };
    status getStatus() const;
    void setStatus(status const &status);

    virtual bool isSet() const override;

private:
    
    qint64 id;
    bool id_isSet;

    
    SWGCategory category;

    
    QString name;

    
    QList<QString> photo_urls;

    
    QList<SWGTag> tags;

    static QStringList data_status;
    status status;

};

}

#endif /* SWGPet_H_ */
