/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGTag.h
 *
 * A tag for a pet
 */

#ifndef SWGTag_H_
#define SWGTag_H_

#include <QJsonObject>
#include <QStringList>


#include <QString>

#include "SWGObject.h"

namespace Swagger {

class SWGTag: public SWGObject {
public:
    SWGTag();
    SWGTag(QString const &json);
    virtual ~SWGTag();
    void init();
    void cleanup();

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject const &json) override;
    void fromJson(QString const &jsonString) override;

    
    qint64 getId() const;
    void setId(qint64 const &id);

    
    QString getName() const;
    void setName(QString const &name);


    virtual bool isSet() const override;

private:
    
    qint64 id;
    bool id_isSet;

    
    QString name;

};

}

#endif /* SWGTag_H_ */
