/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGUser.h
 *
 * A User who is purchasing from the pet store
 */

#ifndef SWGUser_H_
#define SWGUser_H_

#include <QJsonObject>
#include <QStringList>


#include <QString>

#include "SWGObject.h"

namespace Swagger {

class SWGUser: public SWGObject {
public:
    SWGUser();
    SWGUser(QString const &json);
    virtual ~SWGUser();
    void init();
    void cleanup();

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject const &json) override;
    void fromJson(QString const &jsonString) override;

    
    qint64 getId() const;
    void setId(qint64 const &id);

    
    QString getUsername() const;
    void setUsername(QString const &username);

    
    QString getFirstName() const;
    void setFirstName(QString const &first_name);

    
    QString getLastName() const;
    void setLastName(QString const &last_name);

    
    QString getEmail() const;
    void setEmail(QString const &email);

    
    QString getPassword() const;
    void setPassword(QString const &password);

    
    QString getPhone() const;
    void setPhone(QString const &phone);

    
    qint32 getUserStatus() const;
    void setUserStatus(qint32 const &user_status);


    virtual bool isSet() const override;

private:
    
    qint64 id;
    bool id_isSet;

    
    QString username;

    
    QString first_name;

    
    QString last_name;

    
    QString email;

    
    QString password;

    
    QString phone;

    
    qint32 user_status;
    bool user_status_isSet;

};

}

#endif /* SWGUser_H_ */
